trigger:
  branches:
    include:
      - refs/heads/v0.5.4-mt
resources:
  repositories:
    - repository: CustomPipelineTemplates
      type: git
      name: Engineering Fundamentals/WebXT.Pipeline.Templates
      ref: refs/heads/main
variables:
  - name: PUBLISH_DIR
    value: $(System.DefaultWorkingDirectory)\publish\celeborn
extends:
  template: v1/WebXT.Official.EntryPoint.yml@CustomPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    sdl:
      # Spotbugs fails due to "The filename or extension is too long"
      spotBugs:
        enabled: false
      credscan:
        enabled: true
        suppressionsFile: $(Build.SourcesDirectory)\build\.config\CredScanSuppressions.json
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows
      git:
        submodules: false
        longpaths: true
      codeql:
        compiled:
          enabled: true
        runSourceLanguagesInSourceAnalysis: true
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: stage
        jobs:
          - job: BuildPublishCeleborn
            displayName: Build And Publish Celeborn
            timeoutInMinutes: 0
            variables:
              MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
              MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xss4m -XX:ReservedCodeCacheSize=1g'

            steps:
              - checkout: self

              - task: ComponentGovernanceComponentDetection@0
                displayName: Component Detection

              - task: MavenAuthenticate@0
                displayName: '[ENV] Maven Authenticate'
                inputs:
                  artifactsFeeds: central,MultiTenancy-Test3

              - task: AddBuildTag@1
                displayName: '[ENV] Add build tag $(Build.SourceVersion)'
                inputs:
                  tag: $(Build.SourceVersion)

              - task: Cache@2
                inputs:
                  key: 'maven | "$(Agent.OS)" | **/pom.xml'
                  restoreKeys: |
                    maven | "$(Agent.OS)"
                    maven
                  path: $(MAVEN_CACHE_FOLDER)
                displayName: Cache Maven local repo

              - task: Bash@3
                displayName: '[BUILD] Celeborn'
                inputs:
                  targetType: 'filePath'
                  filePath: build/make-distribution.sh
                  arguments: -DskipTests -Pspark-3.2 -Dscala.version=2.12.10 -Dscala.binary.version=2.12 -Dmaven.plugin.scala.version=3.2.2 -Dmaven.plugin.silencer.version=1.6.0 -Pjdk-8
                env:
                  MAVEN_OPTS: $(MAVEN_OPTS)

              - task: PowerShell@2
                displayName: '[Copy] Prepare the Celeborn build'
                inputs:
                  targetType: 'inline'
                  script: |
                    mkdir $(PUBLISH_DIR)
                    mkdir $(PUBLISH_DIR)\Celeborn_Master
                    mkdir $(PUBLISH_DIR)\Celeborn_Worker
                    Copy-Item -Path $(System.DefaultWorkingDirectory)\dist -Destination $(PUBLISH_DIR)\Celeborn -Recurse
                    $files = @('celeborn.ini', 'GenerateCelebornConfig.ps1', 'startCommon.cmd', 'expand-copy.bat')
                    foreach ($file in $files) { Copy-Item $(System.DefaultWorkingDirectory)\$file $(PUBLISH_DIR)\Celeborn\ }
                    Copy-Item $(System.DefaultWorkingDirectory)\ServiceConfig_celeborn.ini $(PUBLISH_DIR)\Celeborn\ServiceConfig.ini
                    Copy-Item $(System.DefaultWorkingDirectory)\start_celeborn.bat $(PUBLISH_DIR)\Celeborn\start.bat
                    Copy-Item $(System.DefaultWorkingDirectory)\ServiceConfig_master.ini $(PUBLISH_DIR)\Celeborn_Master\ServiceConfig.ini
                    Copy-Item $(System.DefaultWorkingDirectory)\start_master.bat $(PUBLISH_DIR)\Celeborn_Master\start.bat
                    Copy-Item $(System.DefaultWorkingDirectory)\ServiceConfig_worker.ini $(PUBLISH_DIR)\Celeborn_Worker\ServiceConfig.ini
                    Copy-Item $(System.DefaultWorkingDirectory)\start_worker.bat $(PUBLISH_DIR)\Celeborn_Worker\start.bat


              - script: |
                  cd $(PUBLISH_DIR)
                  dir /B /S
                displayName: '[TEMP] Print Artifact Structure'
            templateContext:
              outputs:
                - output: pipelineArtifact
                  displayName: '[PUBLISH] Celeborn Artifact'
                  targetPath: dist
                  artifactName: Celeborn
                - output: artifactsDrop
                  displayName: '[PUBLISH] Celeborn to Artifact Services Drop'
                  dropServiceURI: 'https://msasg.artifacts.visualstudio.com/DefaultCollection'
                  buildNumber: 'mtp/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)'
                  sourcePath: $(PUBLISH_DIR)
                  sbomBuildDropPath: $(PUBLISH_DIR)
                  retentionDays: 90