[Feature]
; Name - DependOn
; Description - A comma-separated list of features consumed
; Value - String list
; Default - (empty)
; DependOn=MTTP,Yarn_Java

; Name - Provide
; Description - A comma-separated list of features provided
; Value - String list
; Default - (empty)
Provide=Mt_Celeborn_Master

[Feature.Provide.Mt_Celeborn_Master]

; Name - Endpoint
; Description - A batch script/executable that is called when this feature is consumed.
; The path is relative to the service folder.
; Value - String (filename)
; Default - (empty)
Endpoint=

; Name - Type
; Description - Type of feature.
; Value - [Default|Host]
; Default - Default
;
; Add Yarn_Java as a service "Default" feature, other services may depend on this.
;
Type=Default

; Name - RestartDependantOnChange
; Description - Whether Service Manager should restart dependents if this feature has changed (provider upgrades, etc)
; Value - Boolean
; Default - False
RestartDependantOnChange=True

[Firewall_Inbound]
; More info: http://sharepoint/sites/autopilot/wiki/Firewall.aspx
CELEBORN_MASTERTCP_Azure = TCP/9872,29097:APFW\AzureVM
CELEBORN_PRIVATETCP_Probe = TCP/9872,29097:168.63.129.16/32,fe80::1234:5678:9abc/128
CELEBORN_PRIVATETCP_Backend = TCP/9872,29097:STAGFW\PRIVATE,STAGFW\PFINFRA

[ServiceAccount]
Privileges=SeCreateSymbolicLinkPrivilege

[JobObjectLimit]
; Limit to 10G of memory 
JobMemoryLimit=10737418240
; Limit to 10% of CPU usage
ProcessorRateControlHardCapPercentage=10

