#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -x

PROJECT_DIR="$(cd "`dirname "$0"`/.."; pwd)"

if [ "$1" == "--web" ]; then
  ${PROJECT_DIR}/build/mvn clean install -pl web
else
  ${PROJECT_DIR}/build/mvn spotless:apply -Pflink-1.16
  ${PROJECT_DIR}/build/mvn spotless:apply -Pflink-1.17
  ${PROJECT_DIR}/build/mvn spotless:apply -Pflink-1.18
  ${PROJECT_DIR}/build/mvn spotless:apply -Pflink-1.19
  ${PROJECT_DIR}/build/mvn spotless:apply -Pflink-1.20
  ${PROJECT_DIR}/build/mvn spotless:apply -Pflink-2.0
  ${PROJECT_DIR}/build/mvn spotless:apply -Pspark-2.4
  ${PROJECT_DIR}/build/mvn spotless:apply -Pspark-3.3
  ${PROJECT_DIR}/build/mvn spotless:apply -Pspark-3.5
  ${PROJECT_DIR}/build/mvn spotless:apply -Pspark-4.0
  ${PROJECT_DIR}/build/mvn spotless:apply -Paws
  ${PROJECT_DIR}/build/mvn spotless:apply -Paliyun
  ${PROJECT_DIR}/build/mvn spotless:apply -Pmr
  ${PROJECT_DIR}/build/mvn spotless:apply -Ptez
fi
