{
 "title": "JVM Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(metrics_JVMCPUTime_Value, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(metrics_jvm_memory_pools_init_Value{instance=~\"${instance}\"}, name)"
    }
   },
   { "name": "interval", "query": "5m,30m,1h,6h,12h,1d,3d,7d" }
  ]
 },
 "panels": [
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_memory_heap_init_Value{instance=~\"${instance}\"}",
     "legendFormat": "init_{{instance}}"
    },
    {
     "expr": "metrics_jvm_memory_heap_used_Value{instance=~\"${instance}\"}",
     "legendFormat": "used_{{instance}}"
    },
    {
     "expr": "metrics_jvm_memory_heap_max_Value{instance=~\"${instance}\"}",
     "legendFormat": "max_{{instance}}"
    },
    {
     "expr": "metrics_jvm_memory_heap_committed_Value{instance=~\"${instance}\"}",
     "legendFormat": "committed_{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_memory_non_heap_init_Value{instance=~\"${instance}\"}",
     "legendFormat": "init_{{instance}}"
    },
    {
     "expr": "metrics_jvm_memory_non_heap_used_Value{instance=~\"${instance}\"}",
     "legendFormat": "used_{{instance}}"
    },
    {
     "expr": "metrics_jvm_memory_non_heap_max_Value{instance=~\"${instance}\"}",
     "legendFormat": "max_{{instance}}"
    },
    {
     "expr": "metrics_jvm_memory_non_heap_committed_Value{instance=~\"${instance}\"}",
     "legendFormat": "committed_{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_memory_total_init_Value{instance=~\"${instance}\"}",
     "legendFormat": "init_{{instance}}"
    },
    {
     "expr": "metrics_jvm_memory_total_used_Value{instance=~\"${instance}\"}",
     "legendFormat": "used_{{instance}}"
    },
    {
     "expr": "metrics_jvm_memory_total_max_Value{instance=~\"${instance}\"}",
     "legendFormat": "max_{{instance}}"
    },
    {
     "expr": "metrics_jvm_memory_total_committed_Value{instance=~\"${instance}\"}",
     "legendFormat": "committed_{{instance}}"
    }
   ]
  },
  { "title": "JVM Memory Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "repeat": "pool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_memory_pools_init_Value{instance=~\"${instance}\", name=~\"$pool\"}",
     "legendFormat": "init_{{instance}}"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_memory_pools_used_Value{instance=~\"${instance}\", name=~\"$pool\"}",
     "legendFormat": "used_{{instance}}"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_memory_pools_max_Value{instance=~\"${instance}\", name=~\"$pool\"}",
     "legendFormat": "max_{{instance}}"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_memory_pools_committed_Value{instance=~\"${instance}\", name=~\"$pool\"}",
     "legendFormat": "committed_{{instance}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Collection Time Increase[${interval}]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "increase(metrics_jvm_gc_time_Value{instance=~\"${instance}\"}[${interval}])",
     "legendFormat": "{{name}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Collection Counts Increase[${interval}]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "increase(metrics_jvm_gc_count_Value{instance=~\"${instance}\"}[${interval}])",
     "legendFormat": "{{name}}_{{instance}}"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "CPU Usage Increase[${interval}]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "increase(metrics_JVMCPUTime_Value{instance=~\"${instance}\"}[${interval}])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 46 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_LastMinuteSystemLoad_Value{instance=~\"${instance}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Processors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 46 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_AvailableProcessors_Value{instance=~\"${instance}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thread Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_thread_count_Value{instance=~\"${instance}\"}",
     "legendFormat": "total_{{instance}}"
    },
    {
     "expr": "metrics_jvm_thread_daemon_count_Value{instance=~\"${instance}\"}",
     "legendFormat": "daemon_{{instance}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_thread_blocked_count_Value{instance=~\"${instance}\"}",
     "legendFormat": "blocked_{{instance}}"
    },
    {
     "expr": "metrics_jvm_thread_new_count_Value{instance=~\"${instance}\"}",
     "legendFormat": "new_{{instance}}"
    },
    {
     "expr": "metrics_jvm_thread_runnable_count_Value{instance=~\"${instance}\"}",
     "legendFormat": "runnable_{{instance}}"
    },
    {
     "expr": "metrics_jvm_thread_timed_waiting_count_Value{instance=~\"${instance}\"}",
     "legendFormat": "timed_waiting_{{instance}}"
    },
    {
     "expr": "metrics_jvm_thread_waiting_count_Value{instance=~\"${instance}\"}",
     "legendFormat": "waiting_{{instance}}"
    },
    {
     "expr": "metrics_jvm_thread_terminated_count_Value{instance=~\"${instance}\"}",
     "legendFormat": "terminated_{{instance}}"
    },
    {
     "expr": "metrics_jvm_thread_deadlock_count_Value{instance=~\"${instance}\"}",
     "legendFormat": "deadlock_{{instance}}"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_direct_capacity_Value{instance=~\"${instance}\"}",
     "legendFormat": "capacity_{{instance}}"
    },
    {
     "expr": "metrics_jvm_direct_used_Value{instance=~\"${instance}\"}",
     "legendFormat": "used_{{instance}}"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_direct_count_Value{instance=~\"${instance}\"}",
     "legendFormat": "count_{{instance}}"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_mapped_capacity_Value{instance=~\"${instance}\"}",
     "legendFormat": "capacity_{{instance}}"
    },
    {
     "expr": "metrics_jvm_mapped_used_Value{instance=~\"${instance}\"}",
     "legendFormat": "used_{{instance}}"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "metrics_jvm_mapped_count_Value{instance=~\"${instance}\"}",
     "legendFormat": "count_{{instance}}"
    }
   ]
  }
 ]
}