/*
 * Flink SQL Gateway REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1/1.16
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ConstraintType
 */
@JsonAdapter(ConstraintType.Adapter.class)
public enum ConstraintType {
  
  PRIMARY_KEY("PRIMARY_KEY"),
  
  UNIQUE_KEY("UNIQUE_KEY");

  private String value;

  ConstraintType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ConstraintType fromValue(String value) {
    for (ConstraintType b : ConstraintType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ConstraintType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ConstraintType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ConstraintType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ConstraintType.fromValue(value);
    }
  }
}

