/*
 * Flink SQL Gateway REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1/1.16
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ExecuteStatementResponseBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ExecuteStatementResponseBody {
  public static final String SERIALIZED_NAME_OPERATION_HANDLE = "operationHandle";
  @SerializedName(SERIALIZED_NAME_OPERATION_HANDLE)
  private String operationHandle;


  public ExecuteStatementResponseBody operationHandle(String operationHandle) {
    
    this.operationHandle = operationHandle;
    return this;
  }

   /**
   * Get operationHandle
   * @return operationHandle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOperationHandle() {
    return operationHandle;
  }


  public void setOperationHandle(String operationHandle) {
    this.operationHandle = operationHandle;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecuteStatementResponseBody executeStatementResponseBody = (ExecuteStatementResponseBody) o;
    return Objects.equals(this.operationHandle, executeStatementResponseBody.operationHandle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationHandle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecuteStatementResponseBody {\n");
    sb.append("    operationHandle: ").append(toIndentedString(operationHandle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

