/*
 * Flink SQL Gateway REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1/1.16
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.celeborn.client.model.ResultSet;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.apache.celeborn.client.JSON;


/**
 * FetchResultsResponseBody
 */
@JsonPropertyOrder({
  FetchResultsResponseBody.JSON_PROPERTY_RESULTS,
  FetchResultsResponseBody.JSON_PROPERTY_RESULT_TYPE,
  FetchResultsResponseBody.JSON_PROPERTY_NEXT_RESULT_URI
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FetchResultsResponseBody {
  public static final String JSON_PROPERTY_RESULTS = "results";
  private ResultSet results;

  public static final String JSON_PROPERTY_RESULT_TYPE = "resultType";
  private String resultType;

  public static final String JSON_PROPERTY_NEXT_RESULT_URI = "nextResultUri";
  private String nextResultUri;


  public FetchResultsResponseBody results(ResultSet results) {
    this.results = results;
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResultSet getResults() {
    return results;
  }


  public void setResults(ResultSet results) {
    this.results = results;
  }


  public FetchResultsResponseBody resultType(String resultType) {
    this.resultType = resultType;
    return this;
  }

   /**
   * Get resultType
   * @return resultType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESULT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResultType() {
    return resultType;
  }


  public void setResultType(String resultType) {
    this.resultType = resultType;
  }


  public FetchResultsResponseBody nextResultUri(String nextResultUri) {
    this.nextResultUri = nextResultUri;
    return this;
  }

   /**
   * Get nextResultUri
   * @return nextResultUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NEXT_RESULT_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextResultUri() {
    return nextResultUri;
  }


  public void setNextResultUri(String nextResultUri) {
    this.nextResultUri = nextResultUri;
  }


  /**
   * Return true if this FetchResultsResponseBody object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FetchResultsResponseBody fetchResultsResponseBody = (FetchResultsResponseBody) o;
    return Objects.equals(this.results, fetchResultsResponseBody.results) &&
        Objects.equals(this.resultType, fetchResultsResponseBody.resultType) &&
        Objects.equals(this.nextResultUri, fetchResultsResponseBody.nextResultUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(results, resultType, nextResultUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FetchResultsResponseBody {\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    resultType: ").append(toIndentedString(resultType)).append("\n");
    sb.append("    nextResultUri: ").append(toIndentedString(nextResultUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

