/*
 * Flink SQL Gateway REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1/1.16
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.apache.celeborn.client.JSON;


/**
 * OpenSessionResponseBody
 */
@JsonPropertyOrder({
  OpenSessionResponseBody.JSON_PROPERTY_SESSION_HANDLE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OpenSessionResponseBody {
  public static final String JSON_PROPERTY_SESSION_HANDLE = "sessionHandle";
  private String sessionHandle;


  public OpenSessionResponseBody sessionHandle(String sessionHandle) {
    this.sessionHandle = sessionHandle;
    return this;
  }

   /**
   * Get sessionHandle
   * @return sessionHandle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SESSION_HANDLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionHandle() {
    return sessionHandle;
  }


  public void setSessionHandle(String sessionHandle) {
    this.sessionHandle = sessionHandle;
  }


  /**
   * Return true if this OpenSessionResponseBody object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenSessionResponseBody openSessionResponseBody = (OpenSessionResponseBody) o;
    return Objects.equals(this.sessionHandle, openSessionResponseBody.sessionHandle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionHandle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenSessionResponseBody {\n");
    sb.append("    sessionHandle: ").append(toIndentedString(sessionHandle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

