/*
 * Flink SQL Gateway REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1/1.16
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OpenSessionResponseBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OpenSessionResponseBody {
  public static final String SERIALIZED_NAME_SESSION_HANDLE = "sessionHandle";
  @SerializedName(SERIALIZED_NAME_SESSION_HANDLE)
  private String sessionHandle;


  public OpenSessionResponseBody sessionHandle(String sessionHandle) {
    
    this.sessionHandle = sessionHandle;
    return this;
  }

   /**
   * Get sessionHandle
   * @return sessionHandle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSessionHandle() {
    return sessionHandle;
  }


  public void setSessionHandle(String sessionHandle) {
    this.sessionHandle = sessionHandle;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenSessionResponseBody openSessionResponseBody = (OpenSessionResponseBody) o;
    return Objects.equals(this.sessionHandle, openSessionResponseBody.sessionHandle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionHandle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenSessionResponseBody {\n");
    sb.append("    sessionHandle: ").append(toIndentedString(sessionHandle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

