/*
 * Flink SQL Gateway REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1/1.16
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.apache.celeborn.client.model.DataType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.apache.celeborn.client.JSON;


/**
 * ResolvedExpression
 */
@JsonPropertyOrder({
  ResolvedExpression.JSON_PROPERTY_OUTPUT_DATA_TYPE,
  ResolvedExpression.JSON_PROPERTY_RESOLVED_CHILDREN,
  ResolvedExpression.JSON_PROPERTY_CHILDREN
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ResolvedExpression {
  public static final String JSON_PROPERTY_OUTPUT_DATA_TYPE = "outputDataType";
  private DataType outputDataType;

  public static final String JSON_PROPERTY_RESOLVED_CHILDREN = "resolvedChildren";
  private List<ResolvedExpression> resolvedChildren = null;

  public static final String JSON_PROPERTY_CHILDREN = "children";
  private List<Object> children = null;


  public ResolvedExpression outputDataType(DataType outputDataType) {
    this.outputDataType = outputDataType;
    return this;
  }

   /**
   * Get outputDataType
   * @return outputDataType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OUTPUT_DATA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DataType getOutputDataType() {
    return outputDataType;
  }


  public void setOutputDataType(DataType outputDataType) {
    this.outputDataType = outputDataType;
  }


  public ResolvedExpression resolvedChildren(List<ResolvedExpression> resolvedChildren) {
    this.resolvedChildren = resolvedChildren;
    return this;
  }

  public ResolvedExpression addResolvedChildrenItem(ResolvedExpression resolvedChildrenItem) {
    if (this.resolvedChildren == null) {
      this.resolvedChildren = new ArrayList<>();
    }
    this.resolvedChildren.add(resolvedChildrenItem);
    return this;
  }

   /**
   * Get resolvedChildren
   * @return resolvedChildren
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESOLVED_CHILDREN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ResolvedExpression> getResolvedChildren() {
    return resolvedChildren;
  }


  public void setResolvedChildren(List<ResolvedExpression> resolvedChildren) {
    this.resolvedChildren = resolvedChildren;
  }


  public ResolvedExpression children(List<Object> children) {
    this.children = children;
    return this;
  }

  public ResolvedExpression addChildrenItem(Object childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHILDREN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getChildren() {
    return children;
  }


  public void setChildren(List<Object> children) {
    this.children = children;
  }


  /**
   * Return true if this ResolvedExpression object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResolvedExpression resolvedExpression = (ResolvedExpression) o;
    return Objects.equals(this.outputDataType, resolvedExpression.outputDataType) &&
        Objects.equals(this.resolvedChildren, resolvedExpression.resolvedChildren) &&
        Objects.equals(this.children, resolvedExpression.children);
  }

  @Override
  public int hashCode() {
    return Objects.hash(outputDataType, resolvedChildren, children);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResolvedExpression {\n");
    sb.append("    outputDataType: ").append(toIndentedString(outputDataType)).append("\n");
    sb.append("    resolvedChildren: ").append(toIndentedString(resolvedChildren)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

