/*
 * Celeborn Master REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: user@celeborn.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.celeborn.client.JSON;

/**
 * ShuffleResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.6.0")
public class ShuffleResponse {
  public static final String SERIALIZED_NAME_SHUFFLE_IDS = "shuffleIds";
  @SerializedName(SERIALIZED_NAME_SHUFFLE_IDS)
  private List<String> shuffleIds = new ArrayList<>();

  public ShuffleResponse() {
  }

  public ShuffleResponse shuffleIds(List<String> shuffleIds) {
    this.shuffleIds = shuffleIds;
    return this;
  }

  public ShuffleResponse addShuffleIdsItem(String shuffleIdsItem) {
    if (this.shuffleIds == null) {
      this.shuffleIds = new ArrayList<>();
    }
    this.shuffleIds.add(shuffleIdsItem);
    return this;
  }

   /**
   * The shuffle ids.
   * @return shuffleIds
  **/
  @javax.annotation.Nullable
  public List<String> getShuffleIds() {
    return shuffleIds;
  }

  public void setShuffleIds(List<String> shuffleIds) {
    this.shuffleIds = shuffleIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShuffleResponse shuffleResponse = (ShuffleResponse) o;
    return Objects.equals(this.shuffleIds, shuffleResponse.shuffleIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shuffleIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShuffleResponse {\n");
    sb.append("    shuffleIds: ").append(toIndentedString(shuffleIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("shuffleIds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ShuffleResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ShuffleResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ShuffleResponse is not found in the empty JSON string", ShuffleResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ShuffleResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ShuffleResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("shuffleIds") != null && !jsonObj.get("shuffleIds").isJsonNull() && !jsonObj.get("shuffleIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `shuffleIds` to be an array in the JSON string but got `%s`", jsonObj.get("shuffleIds").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ShuffleResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ShuffleResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ShuffleResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ShuffleResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ShuffleResponse>() {
           @Override
           public void write(JsonWriter out, ShuffleResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ShuffleResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ShuffleResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ShuffleResponse
  * @throws IOException if the JSON string is invalid with respect to ShuffleResponse
  */
  public static ShuffleResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ShuffleResponse.class);
  }

 /**
  * Convert an instance of ShuffleResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

