/*
 * Celeborn Master REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: user@celeborn.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.apache.celeborn.client.model.ThreadStack;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.celeborn.client.JSON;

/**
 * ThreadStackResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.6.0")
public class ThreadStackResponse {
  public static final String SERIALIZED_NAME_THREAD_STACKS = "threadStacks";
  @SerializedName(SERIALIZED_NAME_THREAD_STACKS)
  private List<ThreadStack> threadStacks = new ArrayList<>();

  public ThreadStackResponse() {
  }

  public ThreadStackResponse threadStacks(List<ThreadStack> threadStacks) {
    this.threadStacks = threadStacks;
    return this;
  }

  public ThreadStackResponse addThreadStacksItem(ThreadStack threadStacksItem) {
    if (this.threadStacks == null) {
      this.threadStacks = new ArrayList<>();
    }
    this.threadStacks.add(threadStacksItem);
    return this;
  }

   /**
   * Get threadStacks
   * @return threadStacks
  **/
  @javax.annotation.Nonnull
  public List<ThreadStack> getThreadStacks() {
    return threadStacks;
  }

  public void setThreadStacks(List<ThreadStack> threadStacks) {
    this.threadStacks = threadStacks;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreadStackResponse threadStackResponse = (ThreadStackResponse) o;
    return Objects.equals(this.threadStacks, threadStackResponse.threadStacks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(threadStacks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreadStackResponse {\n");
    sb.append("    threadStacks: ").append(toIndentedString(threadStacks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("threadStacks");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("threadStacks");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ThreadStackResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ThreadStackResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ThreadStackResponse is not found in the empty JSON string", ThreadStackResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ThreadStackResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ThreadStackResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ThreadStackResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("threadStacks").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `threadStacks` to be an array in the JSON string but got `%s`", jsonObj.get("threadStacks").toString()));
      }

      JsonArray jsonArraythreadStacks = jsonObj.getAsJsonArray("threadStacks");
      // validate the required field `threadStacks` (array)
      for (int i = 0; i < jsonArraythreadStacks.size(); i++) {
        ThreadStack.validateJsonElement(jsonArraythreadStacks.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ThreadStackResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ThreadStackResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ThreadStackResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ThreadStackResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ThreadStackResponse>() {
           @Override
           public void write(JsonWriter out, ThreadStackResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ThreadStackResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ThreadStackResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ThreadStackResponse
  * @throws IOException if the JSON string is invalid with respect to ThreadStackResponse
  */
  public static ThreadStackResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ThreadStackResponse.class);
  }

 /**
  * Convert an instance of ThreadStackResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

