/*
 * Flink SQL Gateway REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1/1.16
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.apache.celeborn.client.model.ResolvedExpression;

/**
 * WatermarkSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WatermarkSpec {
  public static final String SERIALIZED_NAME_ROWTIME_ATTRIBUTE = "rowtimeAttribute";
  @SerializedName(SERIALIZED_NAME_ROWTIME_ATTRIBUTE)
  private String rowtimeAttribute;

  public static final String SERIALIZED_NAME_WATERMARK_EXPRESSION = "watermarkExpression";
  @SerializedName(SERIALIZED_NAME_WATERMARK_EXPRESSION)
  private ResolvedExpression watermarkExpression;


  public WatermarkSpec rowtimeAttribute(String rowtimeAttribute) {
    
    this.rowtimeAttribute = rowtimeAttribute;
    return this;
  }

   /**
   * Get rowtimeAttribute
   * @return rowtimeAttribute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRowtimeAttribute() {
    return rowtimeAttribute;
  }


  public void setRowtimeAttribute(String rowtimeAttribute) {
    this.rowtimeAttribute = rowtimeAttribute;
  }


  public WatermarkSpec watermarkExpression(ResolvedExpression watermarkExpression) {
    
    this.watermarkExpression = watermarkExpression;
    return this;
  }

   /**
   * Get watermarkExpression
   * @return watermarkExpression
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ResolvedExpression getWatermarkExpression() {
    return watermarkExpression;
  }


  public void setWatermarkExpression(ResolvedExpression watermarkExpression) {
    this.watermarkExpression = watermarkExpression;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WatermarkSpec watermarkSpec = (WatermarkSpec) o;
    return Objects.equals(this.rowtimeAttribute, watermarkSpec.rowtimeAttribute) &&
        Objects.equals(this.watermarkExpression, watermarkSpec.watermarkExpression);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rowtimeAttribute, watermarkExpression);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WatermarkSpec {\n");
    sb.append("    rowtimeAttribute: ").append(toIndentedString(rowtimeAttribute)).append("\n");
    sb.append("    watermarkExpression: ").append(toIndentedString(watermarkExpression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

