/*
 * Celeborn REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.server.common.http.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import org.apache.celeborn.server.common.http.v1.model.ConfigData;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.apache.celeborn.server.common.http.v1.JSON;


/**
 * DynamicConfig
 */
@JsonPropertyOrder({
  DynamicConfig.JSON_PROPERTY_LEVEL,
  DynamicConfig.JSON_PROPERTY_DESC,
  DynamicConfig.JSON_PROPERTY_CONFIGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DynamicConfig {
  /**
   * the config level of dynamic configs.
   */
  public enum LevelEnum {
    SYSTEM("SYSTEM"),
    
    TENANT("TENANT"),
    
    TENANT_USER("TENANT_USER");

    private String value;

    LevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LevelEnum fromValue(String value) {
      for (LevelEnum b : LevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LEVEL = "level";
  private LevelEnum level;

  public static final String JSON_PROPERTY_DESC = "desc";
  private String desc;

  public static final String JSON_PROPERTY_CONFIGS = "configs";
  private List<ConfigData> configs = null;

  public DynamicConfig() { 
  }

  public DynamicConfig level(LevelEnum level) {
    this.level = level;
    return this;
  }

   /**
   * the config level of dynamic configs.
   * @return level
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LevelEnum getLevel() {
    return level;
  }


  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLevel(LevelEnum level) {
    this.level = level;
  }


  public DynamicConfig desc(String desc) {
    this.desc = desc;
    return this;
  }

   /**
   * additional description of the dynamic config, such as tenantId and user identifier.
   * @return desc
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDesc() {
    return desc;
  }


  @JsonProperty(JSON_PROPERTY_DESC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDesc(String desc) {
    this.desc = desc;
  }


  public DynamicConfig configs(List<ConfigData> configs) {
    this.configs = configs;
    return this;
  }

  public DynamicConfig addConfigsItem(ConfigData configsItem) {
    if (this.configs == null) {
      this.configs = null;
    }
    this.configs.add(configsItem);
    return this;
  }

   /**
   * the config items.
   * @return configs
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ConfigData> getConfigs() {
    return configs;
  }


  @JsonProperty(JSON_PROPERTY_CONFIGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfigs(List<ConfigData> configs) {
    this.configs = configs;
  }


  /**
   * Return true if this DynamicConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DynamicConfig dynamicConfig = (DynamicConfig) o;
    return Objects.equals(this.level, dynamicConfig.level) &&
        Objects.equals(this.desc, dynamicConfig.desc) &&
        Objects.equals(this.configs, dynamicConfig.configs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(level, desc, configs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DynamicConfig {\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    configs: ").append(toIndentedString(configs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

