/*
 * Celeborn REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.server.common.http.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import org.apache.celeborn.server.common.http.v1.model.MasterCommitData;
import org.apache.celeborn.server.common.http.v1.model.MasterLeader;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.apache.celeborn.server.common.http.v1.JSON;


/**
 * MasterInfoResponse
 */
@JsonPropertyOrder({
  MasterInfoResponse.JSON_PROPERTY_GROUP_ID,
  MasterInfoResponse.JSON_PROPERTY_LEADER,
  MasterInfoResponse.JSON_PROPERTY_MASTER_COMMIT_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MasterInfoResponse {
  public static final String JSON_PROPERTY_GROUP_ID = "groupId";
  private String groupId;

  public static final String JSON_PROPERTY_LEADER = "leader";
  private MasterLeader leader;

  public static final String JSON_PROPERTY_MASTER_COMMIT_INFO = "masterCommitInfo";
  private List<MasterCommitData> masterCommitInfo = null;

  public MasterInfoResponse() { 
  }

  public MasterInfoResponse groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * The group id of the master raft server.
   * @return groupId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getGroupId() {
    return groupId;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }


  public MasterInfoResponse leader(MasterLeader leader) {
    this.leader = leader;
    return this;
  }

   /**
   * Get leader
   * @return leader
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEADER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MasterLeader getLeader() {
    return leader;
  }


  @JsonProperty(JSON_PROPERTY_LEADER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeader(MasterLeader leader) {
    this.leader = leader;
  }


  public MasterInfoResponse masterCommitInfo(List<MasterCommitData> masterCommitInfo) {
    this.masterCommitInfo = masterCommitInfo;
    return this;
  }

  public MasterInfoResponse addMasterCommitInfoItem(MasterCommitData masterCommitInfoItem) {
    if (this.masterCommitInfo == null) {
      this.masterCommitInfo = null;
    }
    this.masterCommitInfo.add(masterCommitInfoItem);
    return this;
  }

   /**
   * The raft commit info of the master.
   * @return masterCommitInfo
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MASTER_COMMIT_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MasterCommitData> getMasterCommitInfo() {
    return masterCommitInfo;
  }


  @JsonProperty(JSON_PROPERTY_MASTER_COMMIT_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMasterCommitInfo(List<MasterCommitData> masterCommitInfo) {
    this.masterCommitInfo = masterCommitInfo;
  }


  /**
   * Return true if this MasterInfoResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MasterInfoResponse masterInfoResponse = (MasterInfoResponse) o;
    return Objects.equals(this.groupId, masterInfoResponse.groupId) &&
        Objects.equals(this.leader, masterInfoResponse.leader) &&
        Objects.equals(this.masterCommitInfo, masterInfoResponse.masterCommitInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupId, leader, masterCommitInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MasterInfoResponse {\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    leader: ").append(toIndentedString(leader)).append("\n");
    sb.append("    masterCommitInfo: ").append(toIndentedString(masterCommitInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

