/*
 * Celeborn REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.celeborn.server.common.http.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.apache.celeborn.server.common.http.v1.JSON;


/**
 * ShufflesResponse
 */
@JsonPropertyOrder({
  ShufflesResponse.JSON_PROPERTY_SHUFFLE_IDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ShufflesResponse {
  public static final String JSON_PROPERTY_SHUFFLE_IDS = "shuffleIds";
  private List<String> shuffleIds = null;

  public ShufflesResponse() { 
  }

  public ShufflesResponse shuffleIds(List<String> shuffleIds) {
    this.shuffleIds = shuffleIds;
    return this;
  }

  public ShufflesResponse addShuffleIdsItem(String shuffleIdsItem) {
    if (this.shuffleIds == null) {
      this.shuffleIds = null;
    }
    this.shuffleIds.add(shuffleIdsItem);
    return this;
  }

   /**
   * The shuffle keys.
   * @return shuffleIds
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHUFFLE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getShuffleIds() {
    return shuffleIds;
  }


  @JsonProperty(JSON_PROPERTY_SHUFFLE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShuffleIds(List<String> shuffleIds) {
    this.shuffleIds = shuffleIds;
  }


  /**
   * Return true if this ShufflesResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShufflesResponse shufflesResponse = (ShufflesResponse) o;
    return Objects.equals(this.shuffleIds, shufflesResponse.shuffleIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shuffleIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShufflesResponse {\n");
    sb.append("    shuffleIds: ").append(toIndentedString(shuffleIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

